#!/usr/bin/env node
// Start the Next dev server against the LOCAL Docker stack's env.
//
//   node scripts/dev-docker.mjs        (or: npm run dev:docker)
//
// This replaces what used to be an inline shell one-liner:
//
//   bash -c 'set -a; . ./.env.docker; set +a; next dev'
//
// which cannot work on Windows for a reason that has nothing to do with bash.
// npm runs scripts through `cmd.exe`, and cmd does not treat `'` as quoting — so
// bash received `'set` as its entire command string. Even with Git Bash properly
// installed and first on PATH, this line was broken; `dev:stack` survived only
// because it happens to contain no quotes.
//
// Reading the file in Node also drops a bash dependency from the one command a
// self-hoster runs every single day.
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const envPath = path.join(root, ".env.docker");

// Deliberately matches `set -a; . ./.env.docker` and not dotenv: a value in the
// FILE wins over one already in the environment, because sourcing assigns
// unconditionally. Inverting that would make a stale exported VISA_SECRET in the
// operator's shell silently outrank the one the stack actually generated.
export function parseEnvFile(contents) {
  const values = {};
  for (const rawLine of contents.split(/\r?\n/)) {
    const line = rawLine.trim();
    if (!line || line.startsWith("#")) continue;
    const withoutExport = line.startsWith("export ") ? line.slice(7).trim() : line;
    const eq = withoutExport.indexOf("=");
    if (eq <= 0) continue;
    const key = withoutExport.slice(0, eq).trim();
    if (!/^[A-Za-z_][A-Za-z0-9_]*$/.test(key)) continue;
    let value = withoutExport.slice(eq + 1).trim();
    // dev-stack.sh writes bare values, but a hand-edited file may quote one.
    if (
      value.length >= 2 &&
      ((value.startsWith('"') && value.endsWith('"')) || (value.startsWith("'") && value.endsWith("'")))
    ) {
      value = value.slice(1, -1);
    }
    // Empty is a real, meaningful value here — INSTANCE_SIGNING_KEY_PREV is
    // empty until an actual rotation fills it, and that is not the same as
    // inheriting whatever the shell happens to carry.
    values[key] = value;
  }
  return values;
}

function missingEnvMessage() {
  return [
    "✗ .env.docker not found.",
    "",
    "  It is generated by the local stack bootstrap. Run:",
    "      npm run dev:stack",
    "",
    "  Without it the dev server starts and then throws",
    '  "Your project\'s URL and Key are required to create a Supabase client"',
    "  on every request, which reads like a Supabase bug rather than a missing file.",
  ].join("\n");
}

async function main() {
  if (!fs.existsSync(envPath)) {
    console.error(missingEnvMessage());
    process.exit(1);
  }

  Object.assign(process.env, parseEnvFile(fs.readFileSync(envPath, "utf8")));

  // Run Next in THIS process rather than spawning it. One process means the pid
  // the CLI records in its dashboard state is the server itself, so `passcontrol
  // stop` signals the thing it means to — on Windows especially, where stop kills
  // a single pid and not a process tree, so an intermediate npm/cmd wrapper would
  // leave the server running and the port held.
  const nextBin = path.join(root, "node_modules", "next", "dist", "bin", "next");
  if (!fs.existsSync(nextBin)) {
    console.error(`✗ Next.js is not installed (${nextBin} is missing). Run \`npm ci\` first.`);
    process.exit(1);
  }

  process.argv = [process.argv[0], nextBin, "dev", ...process.argv.slice(2)];
  // A bare Windows path is not a valid ESM specifier (`C:` reads as a protocol),
  // so the import goes through a file:// URL on every platform.
  await import(pathToFileURL(nextBin).href);
}

// Importing this file must not start a server — tests exercise parseEnvFile.
// Resolved-path comparison, not a filename match: a substring check would also
// fire under a test runner whose own argv happened to end the same way.
const invokedDirectly =
  process.argv[1] !== undefined &&
  path.resolve(process.argv[1]) === path.resolve(fileURLToPath(import.meta.url));
if (invokedDirectly) await main();
