#!/usr/bin/env bash
# One-command local stack: Supabase (CLI) + Redis/SRH (compose) + migrate + seed.
# Packaging only — no gateway code changes.
#
#   bash scripts/dev-stack.sh          (or: npm run dev:stack)
#
# Prereqs: Docker running + the Supabase CLI. NO host psql needed — migrations run
# inside the Supabase DB container. Afterwards, start the app with the docker env:
#   npm run dev:docker
set -euo pipefail

SRC="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$SRC"
ENVF="$SRC/.env.docker"

# ── 1. Prereqs ────────────────────────────────────────────────────────────────
command -v docker >/dev/null || { echo "✗ docker not found — install Docker Desktop." >&2; exit 1; }
docker info >/dev/null 2>&1 || { echo "✗ Docker daemon not running — start Docker Desktop." >&2; exit 1; }
command -v supabase >/dev/null || { echo "✗ supabase CLI not found — install: brew install supabase/tap/supabase" >&2; exit 1; }
command -v node >/dev/null || { echo "✗ node not found." >&2; exit 1; }

# ── 2. Supabase local stack (Postgres + Vault + Auth + Kong) ──────────────────
# We exclude `studio` — PassControl ships its own dashboard, and Supabase's Studio
# image is flaky here (unhealthy → `supabase start` rolls the whole stack back).
# Studio is a leaf (nothing depends on it), so this is safe; other services are
# left as-is to avoid dependency-health surprises (e.g. analytics ← vector).
echo "→ Starting Supabase local stack (first run pulls images — be patient)…"
supabase start -x studio
# Pull connection details (sets API_URL, ANON_KEY, SERVICE_ROLE_KEY, DB_URL, …)
eval "$(supabase status -o env)"

# ── 3. Redis + SRH (the Upstash-REST piece the CLI doesn't provide) ───────────
echo "→ Starting redis + serverless-redis-http…"
docker compose -f docker/compose.yml up -d >/dev/null

# ── 4. Generate .env.docker (preserve previously generated secrets) ───────────
gen() { openssl rand -base64 32 | tr -d '\n'; }
VISA_SECRET=""; CACHE_ENC_KEY=""; CRON_SECRET=""
if [[ -f "$ENVF" ]]; then
  VISA_SECRET=$(grep '^VISA_SECRET=' "$ENVF" | cut -d= -f2- || true)
  CACHE_ENC_KEY=$(grep '^CACHE_ENC_KEY=' "$ENVF" | cut -d= -f2- || true)
  CRON_SECRET=$(grep '^CRON_SECRET=' "$ENVF" | cut -d= -f2- || true)
fi
VISA_SECRET=${VISA_SECRET:-$(gen)}
CACHE_ENC_KEY=${CACHE_ENC_KEY:-$(gen)}
CRON_SECRET=${CRON_SECRET:-$(gen)}

cat > "$ENVF" <<EOF
# Generated by scripts/dev-stack.sh — LOCAL DEV ONLY. gitignored. Do not commit.
NEXT_PUBLIC_SUPABASE_URL=$API_URL
NEXT_PUBLIC_SUPABASE_ANON_KEY=$ANON_KEY
SUPABASE_SERVICE_ROLE_KEY=$SERVICE_ROLE_KEY
UPSTASH_REDIS_REST_URL=http://localhost:8079
UPSTASH_REDIS_REST_TOKEN=passcontrol_local_dev_token
VISA_SECRET=$VISA_SECRET
VISA_TTL_SECONDS=300
CACHE_ENC_KEY=$CACHE_ENC_KEY
CRON_SECRET=$CRON_SECRET
INVITE_CODE=local-dev
DEV_USER_EMAIL=dev@passcontrol.local
DEV_USER_PASSWORD=passcontrol-dev
EOF
echo "→ Wrote .env.docker"

# ── 5. Migrations — run INSIDE the Supabase DB container (no host psql needed) ─
# Mirrors scripts/migrate.sh's ledger, but via docker exec. Each file + its
# ledger insert run in ONE transaction (psql -1) so a non-idempotent migration
# (e.g. 0005) can never be half-applied.
DBC=$(docker ps --filter name=supabase_db --format '{{.Names}}' | head -1)
[[ -n "$DBC" ]] || { echo "✗ Could not find the Supabase DB container." >&2; exit 1; }
PSQL=(docker exec -i "$DBC" psql -U postgres -d postgres -v ON_ERROR_STOP=1)
echo "→ Applying migrations (in $DBC)…"
"${PSQL[@]}" -q -c "create table if not exists public.schema_migrations (version text primary key, applied_at timestamptz default now());"
for f in db/migrations/*.sql; do
  v="$(basename "$f")"
  applied="$("${PSQL[@]}" -tAc "select 1 from public.schema_migrations where version='$v'" || true)"
  if [[ "$applied" == "1" ]]; then echo "  = $v (already applied)"; continue; fi
  echo "  + $v"
  { cat "$f"; printf "\ninsert into public.schema_migrations (version) values ('%s');\n" "$v"; } | "${PSQL[@]}" -1 -q
done

# ── 6. Seed a confirmed dev user ──────────────────────────────────────────────
echo "→ Seeding dev user…"
set -a; . "$ENVF"; set +a
node scripts/seed.mjs

# ── 7. Done ───────────────────────────────────────────────────────────────────
cat <<DONE

✅ Local stack is up.
   Supabase API    : ${API_URL}   (Studio UI is excluded — use the PassControl dashboard)
   Start the app   : npm run dev:docker
                     → http://localhost:3000  (log in: dev@passcontrol.local / passcontrol-dev)

   Then: add a provider key + issue a passport in the dashboard, and run:
         node examples/chat-agent.mjs "Say hi in 3 words"

   Stop everything : supabase stop && docker compose -f docker/compose.yml down -v
DONE
