import { LegalContact, LegalPage } from "@/components/legal/LegalPage";

export const metadata = { title: "Free beta terms" };

export default function TermsPage() {
  return (
    <LegalPage title="Free beta terms." summary="The terms for invited users of the free PassControl Cloud beta. Self-hosted software remains governed by its source licence.">
      <section><h2>1. The agreement</h2><p>These terms are between you and Kristiyan Ivanov, the individual operating the Vertias project. By creating or using an invited PassControl Cloud account after these terms become effective, you agree to them and the acceptable use policy. You must be at least 18 and able to enter this agreement.</p><LegalContact /></section>
      <section><h2>2. The beta</h2><p>PassControl Cloud is a free, invite-only, experimental service. An invitation is personal and does not guarantee continued access. Features, limits and availability may change, and the service may be paused or withdrawn. There is no service-level agreement.</p><p>No paid PassControl subscription is being sold under these terms. Your model providers may still charge you for calls PassControl sends using your credentials.</p></section>
      <section><h2>3. Your account and credentials</h2><ul><li>Keep operator sessions, agent credentials, recovery codes and provider keys secure.</li><li>Use separate, non-critical provider credentials with limits set at the provider where possible.</li><li>You are responsible for activity under your account and for promptly reporting suspected compromise.</li><li>You may not transfer an invite or give another person access without permission.</li></ul></section>
      <section><h2>4. What PassControl does</h2><p>PassControl checks configured identity, scope, policy, rate limit, suspension, kill state and budget controls before dispatching supported model calls. These controls reduce risk; they do not guarantee that an agent, model, provider, network or configuration will behave safely.</p><p>PassControl is not designed for emergency, safety-critical, medical, legal, financial or other regulated decision-making.</p></section>
      <section><h2>5. Your responsibilities</h2><p>You are responsible for the agents, prompts, content, provider accounts, configuration, outputs and laws that apply to your use. You must have the rights and permissions needed for data you route through the service and must follow each provider's terms.</p></section>
      <section><h2>6. Content and service operation</h2><p>You retain rights in content you submit. You grant only the limited rights needed to process, transmit and secure that content, provide the service and comply with law. PassControl does not claim ownership of your prompts or outputs.</p><p>Service access may be limited or suspended to protect users or infrastructure, enforce these terms, investigate abuse, respond to law, or operate the beta.</p></section>
      <section><h2>7. Source code and brands</h2><p>Use of the self-hosted source is governed separately by the Business Source License 1.1 in the repository. These beta terms do not grant rights to the Vertias or PassControl names, logos or other brand assets.</p></section>
      <section><h2>8. Ending use</h2><p>You may stop using the beta at any time. An authenticated operator can export account data and permanently delete the workspace from Dashboard → Settings → Account data. Access may be ended for breach, security risk, legal necessity, prolonged inactivity or discontinuation of the beta. Reasonable notice will be given where practical and safe.</p></section>
      <section><h2>9. Disclaimers and liability</h2><p>The beta is provided “as is” and “as available,” to the fullest extent permitted by law. No guarantee is made that it will be uninterrupted, error-free, secure against every attack, or suitable for your purpose.</p><p>To the fullest extent permitted by law, Kristiyan Ivanov is not liable for indirect, incidental, special or consequential loss, lost profits, lost data, model outputs, provider charges or business interruption arising from the free beta. Nothing excludes liability that cannot lawfully be excluded, or any mandatory consumer right.</p></section>
      <section><h2>10. Law and changes</h2><p>Bulgarian law governs these terms, subject to mandatory protections and jurisdiction rights that apply to you. Material changes will be communicated before they take effect; continued use after that date means acceptance.</p></section>
      <section><h2>11. Contact</h2><p>Questions, notices and deletion assistance: <a href="mailto:hello@vertias.eu">hello@vertias.eu</a>.</p></section>
    </LegalPage>
  );
}
